// Generated by gencpp from file gas_robot_sim/Greeting.msg
// DO NOT EDIT!


#ifndef GAS_ROBOT_SIM_MESSAGE_GREETING_H
#define GAS_ROBOT_SIM_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <gas_robot_sim/GreetingRequest.h>
#include <gas_robot_sim/GreetingResponse.h>


namespace gas_robot_sim
{

struct Greeting
{

typedef GreetingRequest Request;
typedef GreetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Greeting
} // namespace gas_robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gas_robot_sim::Greeting > {
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::gas_robot_sim::Greeting&) { return value(); }
};

template<>
struct DataType< ::gas_robot_sim::Greeting > {
  static const char* value()
  {
    return "gas_robot_sim/Greeting";
  }

  static const char* value(const ::gas_robot_sim::Greeting&) { return value(); }
};


// service_traits::MD5Sum< ::gas_robot_sim::GreetingRequest> should match
// service_traits::MD5Sum< ::gas_robot_sim::Greeting >
template<>
struct MD5Sum< ::gas_robot_sim::GreetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gas_robot_sim::Greeting >::value();
  }
  static const char* value(const ::gas_robot_sim::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gas_robot_sim::GreetingRequest> should match
// service_traits::DataType< ::gas_robot_sim::Greeting >
template<>
struct DataType< ::gas_robot_sim::GreetingRequest>
{
  static const char* value()
  {
    return DataType< ::gas_robot_sim::Greeting >::value();
  }
  static const char* value(const ::gas_robot_sim::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gas_robot_sim::GreetingResponse> should match
// service_traits::MD5Sum< ::gas_robot_sim::Greeting >
template<>
struct MD5Sum< ::gas_robot_sim::GreetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gas_robot_sim::Greeting >::value();
  }
  static const char* value(const ::gas_robot_sim::GreetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gas_robot_sim::GreetingResponse> should match
// service_traits::DataType< ::gas_robot_sim::Greeting >
template<>
struct DataType< ::gas_robot_sim::GreetingResponse>
{
  static const char* value()
  {
    return DataType< ::gas_robot_sim::Greeting >::value();
  }
  static const char* value(const ::gas_robot_sim::GreetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAS_ROBOT_SIM_MESSAGE_GREETING_H
