// Generated by gencpp from file gas_robot_sim/GreetingResponse.msg
// DO NOT EDIT!


#ifndef GAS_ROBOT_SIM_MESSAGE_GREETINGRESPONSE_H
#define GAS_ROBOT_SIM_MESSAGE_GREETINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gas_robot_sim
{
template <class ContainerAllocator>
struct GreetingResponse_
{
  typedef GreetingResponse_<ContainerAllocator> Type;

  GreetingResponse_()
    : message()  {
    }
  GreetingResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GreetingResponse_

typedef ::gas_robot_sim::GreetingResponse_<std::allocator<void> > GreetingResponse;

typedef boost::shared_ptr< ::gas_robot_sim::GreetingResponse > GreetingResponsePtr;
typedef boost::shared_ptr< ::gas_robot_sim::GreetingResponse const> GreetingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gas_robot_sim::GreetingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gas_robot_sim::GreetingResponse_<ContainerAllocator1> & lhs, const ::gas_robot_sim::GreetingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gas_robot_sim::GreetingResponse_<ContainerAllocator1> & lhs, const ::gas_robot_sim::GreetingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gas_robot_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::gas_robot_sim::GreetingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gas_robot_sim/GreetingResponse";
  }

  static const char* value(const ::gas_robot_sim::GreetingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"\n"
;
  }

  static const char* value(const ::gas_robot_sim::GreetingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GreetingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gas_robot_sim::GreetingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gas_robot_sim::GreetingResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAS_ROBOT_SIM_MESSAGE_GREETINGRESPONSE_H
