// Generated by gencpp from file gas_robot_sim/GreetingRequest.msg
// DO NOT EDIT!


#ifndef GAS_ROBOT_SIM_MESSAGE_GREETINGREQUEST_H
#define GAS_ROBOT_SIM_MESSAGE_GREETINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gas_robot_sim
{
template <class ContainerAllocator>
struct GreetingRequest_
{
  typedef GreetingRequest_<ContainerAllocator> Type;

  GreetingRequest_()
    {
    }
  GreetingRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GreetingRequest_

typedef ::gas_robot_sim::GreetingRequest_<std::allocator<void> > GreetingRequest;

typedef boost::shared_ptr< ::gas_robot_sim::GreetingRequest > GreetingRequestPtr;
typedef boost::shared_ptr< ::gas_robot_sim::GreetingRequest const> GreetingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gas_robot_sim::GreetingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gas_robot_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gas_robot_sim::GreetingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gas_robot_sim/GreetingRequest";
  }

  static const char* value(const ::gas_robot_sim::GreetingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gas_robot_sim::GreetingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GreetingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gas_robot_sim::GreetingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gas_robot_sim::GreetingRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GAS_ROBOT_SIM_MESSAGE_GREETINGREQUEST_H
